apiVersion: apps/v1
kind: Deployment
metadata:
  name: soe-chobot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: soe-chobot
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: soe-chobot
        image: ghcr.io/sigmasuite/chobot:main
        imagePullPolicy: Always
        env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: DISCORD_TOKEN
                  name: discord-secrets
            - name: STREAM_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: STREAM_ADDRESS
                  name: discord-secrets
  selector:
    matchLabels:
      app: soe-chobot
